FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/defalt.conf
COPY code /usr/share/nginx/html/
COPY expense.conf /etc/nginx/nginx.conf
