FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
COPY code /usr/share/nginx/html/
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /tec/nginx/conf.d/defalt.conf
COPY expense.conf /etc/nginx/nginx.conf
